import { BriefingTypeConfig } from "@/types/briefing";

// ── Oferta Landing — Formulario simplificado (4 pasos) ──
// Secciones fijas: Hero + Servicios + Galería + FAQ + Contacto
// Precio fijo será inyectado dinámicamente desde la promoción activa

export const ofertaConfig: BriefingTypeConfig = {
    id: "oferta",
    type: "OFERTA",
    label: "Landing Page — Oferta Especial",
    description: "Landing page profesional con secciones predefinidas a precio promocional",
    icon: "Zap",
    enabled: true,
    steps: [
        {
            id: "identity",
            title: "Tu Negocio",
            description: "Cuéntanos sobre ti y tu negocio",
            icon: "Building2",
            fields: [
                {
                    id: "firstName",
                    label: "Tu nombre",
                    type: "text",
                    placeholder: "Ej: Juan",
                    required: true,
                    dataGroup: "contact",
                },
                {
                    id: "lastNameP",
                    label: "Apellido paterno",
                    type: "text",
                    placeholder: "Ej: Pérez",
                    required: true,
                    dataGroup: "contact",
                },
                {
                    id: "lastNameM",
                    label: "Apellido materno (opcional)",
                    type: "text",
                    placeholder: "Ej: González",
                    required: false,
                    dataGroup: "contact",
                },
                {
                    id: "businessName",
                    label: "Nombre de tu negocio o marca",
                    type: "text",
                    placeholder: "Ej: Panadería Don Juan",
                    required: true,
                    dataGroup: "contact",
                },
                {
                    id: "industry",
                    label: "Rubro o industria",
                    type: "select",
                    required: true,
                    dataGroup: "contact",
                    options: [
                        { value: "gastronomia", label: "Gastronomía / Restaurante" },
                        { value: "salud", label: "Salud / Medicina" },
                        { value: "belleza", label: "Belleza / Estética" },
                        { value: "educacion", label: "Educación / Cursos" },
                        { value: "tecnologia", label: "Tecnología / Software" },
                        { value: "inmobiliaria", label: "Inmobiliaria / Bienes raíces" },
                        { value: "legal", label: "Legal / Abogados" },
                        { value: "fitness", label: "Fitness / Deporte" },
                        { value: "construccion", label: "Construcción / Remodelación" },
                        { value: "automotriz", label: "Automotriz" },
                        { value: "agricultura", label: "Agricultura / Agro" },
                        { value: "consultoria", label: "Consultoría / Asesoría" },
                        { value: "marketing", label: "Marketing / Publicidad" },
                        { value: "otro", label: "Otro" },
                    ],
                },
                {
                    id: "email",
                    label: "Correo electrónico de contacto",
                    type: "email",
                    placeholder: "Ej: juan@minegocio.cl",
                    required: true,
                    dataGroup: "contact",
                },
                {
                    id: "phone",
                    label: "Teléfono / WhatsApp",
                    type: "tel",
                    placeholder: "Ej: +56 9 1234 5678",
                    required: false,
                    dataGroup: "contact",
                },
            ],
        },
        {
            id: "objective",
            title: "Objetivo",
            description: "¿Qué quieres lograr con tu landing page?",
            icon: "Target",
            fields: [
                {
                    id: "mainGoal",
                    label: "Objetivo principal de la landing",
                    type: "select",
                    required: true,
                    dataGroup: "content",
                    options: [
                        { value: "captar_leads", label: "Captar clientes potenciales (leads)" },
                        { value: "vender_servicio", label: "Promocionar y vender un servicio" },
                        { value: "vender_producto", label: "Promocionar un producto" },
                        { value: "informar", label: "Dar a conocer mi negocio" },
                        { value: "evento", label: "Promocionar un evento" },
                        { value: "portafolio", label: "Mostrar mi portafolio / trabajo" },
                        { value: "otro", label: "Otro" },
                    ],
                },
                {
                    id: "targetAudience",
                    label: "¿Quién es tu cliente ideal?",
                    type: "textarea",
                    placeholder: "Ej: Mujeres de 25-45 años que buscan servicios de belleza en Santiago...",
                    required: true,
                    dataGroup: "content",
                    helperText: "Describe tu público objetivo: edad, género, ubicación, intereses",
                },
                {
                    id: "mainCTA",
                    label: "¿Qué acción principal quieres que tome el visitante?",
                    type: "select",
                    required: true,
                    dataGroup: "content",
                    options: [
                        { value: "whatsapp", label: "Contactar por WhatsApp" },
                        { value: "formulario", label: "Llenar un formulario de contacto" },
                        { value: "llamar", label: "Llamar por teléfono" },
                        { value: "agendar", label: "Agendar una cita / reunión" },
                        { value: "comprar", label: "Comprar un producto / servicio" },
                        { value: "descargar", label: "Descargar algo (PDF, catálogo, etc.)" },
                        { value: "otro", label: "Otro" },
                    ],
                },
                {
                    id: "uniqueValue",
                    label: "¿Qué te hace diferente de tu competencia?",
                    type: "textarea",
                    placeholder: "Ej: 10 años de experiencia, atención personalizada, precios competitivos...",
                    required: false,
                    dataGroup: "content",
                    helperText: "Esto nos ayuda a destacar lo que te hace especial",
                },
            ],
        },
        {
            id: "design",
            title: "Diseño",
            description: "¿Cómo quieres que se vea tu landing page?",
            icon: "Palette",
            fields: [
                {
                    id: "designStyle",
                    label: "Estilo visual que prefieres",
                    type: "select",
                    required: true,
                    dataGroup: "design",
                    options: [
                        { value: "moderno", label: "Moderno y limpio" },
                        { value: "elegante", label: "Elegante y sofisticado" },
                        { value: "minimalista", label: "Minimalista" },
                        { value: "corporativo", label: "Corporativo / Profesional" },
                        { value: "creativo", label: "Creativo y colorido" },
                        { value: "oscuro", label: "Dark mode / Oscuro" },
                        { value: "calido", label: "Cálido y acogedor" },
                        { value: "no_se", label: "No estoy seguro, decídanlo ustedes" },
                    ],
                },
                {
                    id: "primaryColor",
                    label: "Color principal de tu marca",
                    type: "color",
                    required: false,
                    dataGroup: "design",
                    helperText: "Si tienes colores de marca, selecciona el principal",
                },
                {
                    id: "referenceUrls",
                    label: "¿Hay alguna página web que te guste como referencia?",
                    type: "textarea",
                    placeholder: "Pega los links de páginas que te gusten...\nEj: https://ejemplo.com",
                    required: false,
                    dataGroup: "design",
                    helperText: "Nos ayuda a entender el estilo que buscas",
                },
            ],
        },
        {
            id: "content",
            title: "Contenido",
            description: "¿Qué material tienes listo?",
            icon: "FileText",
            fields: [
                {
                    id: "hasLogo",
                    label: "¿Tienes logo?",
                    type: "radio",
                    required: true,
                    dataGroup: "content",
                    options: [
                        { value: "si", label: "Sí, tengo logo listo" },
                        { value: "no_necesito", label: "No tengo, pero lo necesito" },
                        { value: "no_no_necesito", label: "No tengo y no lo necesito por ahora" },
                    ],
                },
                {
                    id: "hasPhotos",
                    label: "¿Tienes fotos propias de tu negocio/productos?",
                    type: "radio",
                    required: true,
                    dataGroup: "content",
                    options: [
                        { value: "si", label: "Sí, tengo fotos propias" },
                        { value: "algunas", label: "Tengo algunas, pero necesitaría más" },
                        { value: "no", label: "No tengo, usen fotos de stock" },
                    ],
                },
                {
                    id: "hasTexts",
                    label: "¿Tienes los textos escritos para la página?",
                    type: "radio",
                    required: true,
                    dataGroup: "content",
                    options: [
                        { value: "si", label: "Sí, están listos" },
                        { value: "borrador", label: "Tengo un borrador / ideas" },
                        { value: "no", label: "No, necesito ayuda con los textos" },
                    ],
                },
                {
                    id: "additionalNotes",
                    label: "¿Algo más que debamos saber sobre tu proyecto?",
                    type: "textarea",
                    placeholder: "Ej: Tengo un catálogo PDF, quiero integrar mi Instagram, necesito que se vea igual a otra web...",
                    required: false,
                    dataGroup: "content",
                    helperText: "Cualquier detalle extra nos ayuda a entregarte exactamente lo que necesitas",
                },
            ],
        },
    ],
};
