import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { I18nProvider } from "@/context/I18nContext";
import { ThemeProvider } from "@/context/ThemeContext";
import { organizationJsonLd, websiteJsonLd, professionalServiceJsonLd } from "@/lib/seo";
import GoogleAnalytics from "@/components/shared/GoogleAnalytics";
import PageTransition from "@/components/shared/PageTransition";
import CookieConsent from "@/components/shared/CookieConsent";
import "./globals.css";

const inter = Inter({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700", "800", "900"],
  variable: "--font-inter",
});

const SITE_URL = "https://www.purocode.com";

export const metadata: Metadata = {
  metadataBase: new URL(SITE_URL),
  title: {
    default: "PuroCode | Agencia de Desarrollo Web & SaaS Premium en Chile",
    template: "%s | PuroCode",
  },
  description:
    "Agencia chilena de desarrollo web profesional. Creamos landing pages, sitios corporativos, e-commerce y soluciones SaaS a medida con Next.js, React y tecnología de vanguardia. Cotiza gratis.",
  keywords: [
    "desarrollo web Chile",
    "agencia desarrollo web",
    "diseño web profesional",
    "landing page Chile",
    "página web empresa",
    "e-commerce Chile",
    "tienda online",
    "desarrollo SaaS",
    "sitio web corporativo",
    "PuroCode",
    "diseño web moderno",
    "Next.js",
    "React",
    "desarrollo web Santiago",
    "crear página web",
    "cotizar página web",
  ],
  authors: [{ name: "PuroCode", url: SITE_URL }],
  creator: "PuroCode",
  publisher: "PuroCode",
  icons: {
    icon: [
      { url: "/img/favicon/favicon.ico" },
      { url: "/img/favicon/favicon-16x16.png", sizes: "16x16", type: "image/png" },
      { url: "/img/favicon/favicon-32x32.png", sizes: "32x32", type: "image/png" },
    ],
    apple: "/img/favicon/apple-touch-icon.png",
  },
  openGraph: {
    type: "website",
    locale: "es_CL",
    url: SITE_URL,
    siteName: "PuroCode",
    title: "PuroCode | Agencia de Desarrollo Web & SaaS Premium en Chile",
    description:
      "Creamos landing pages, sitios corporativos, e-commerce y SaaS a medida con tecnología de vanguardia. Cotiza tu proyecto gratis.",
    // OG image auto-generated by opengraph-image.tsx
  },
  twitter: {
    card: "summary_large_image",
    title: "PuroCode | Desarrollo Web & SaaS Premium",
    description:
      "Agencia chilena de desarrollo web. Landing pages, e-commerce y SaaS a medida. Cotiza gratis.",
    // Twitter image auto-generated by opengraph-image.tsx
  },
  robots: {
    index: true,
    follow: true,
    googleBot: {
      index: true,
      follow: true,
      "max-video-preview": -1,
      "max-image-preview": "large",
      "max-snippet": -1,
    },
  },
  alternates: {
    canonical: SITE_URL,
  },
  verification: {
    google: "IoZ11vA3RD2W6xRSh2o5oJdQMPmKx9evJDnXcFGD-6k",
  },
  category: "technology",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="es" suppressHydrationWarning>
      <head>
        <link rel="manifest" href="/img/favicon/site.webmanifest" />
        <meta name="theme-color" content="#6d28d9" />
        <script
          type="application/ld+json"
          dangerouslySetInnerHTML={{
            __html: JSON.stringify([
              organizationJsonLd,
              websiteJsonLd,
              professionalServiceJsonLd,
            ]),
          }}
        />
      </head>
      <body
        className={`${inter.variable} font-display bg-[var(--bg)] text-[var(--text)] antialiased overflow-x-hidden`}
      >
        <a
          href="#main-content"
          className="sr-only focus:not-sr-only focus:absolute focus:top-4 focus:left-4 focus:z-[9999] focus:bg-[var(--primary)] focus:text-white focus:px-4 focus:py-2 focus:rounded-lg focus:text-sm"
        >
          Saltar al contenido
        </a>
        <ThemeProvider>
          <I18nProvider>
            <PageTransition>{children}</PageTransition>
          </I18nProvider>
        </ThemeProvider>
        <GoogleAnalytics />
        <CookieConsent />
      </body>
    </html>
  );
}
